[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["isomo"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
uuid = { version = "1.4", features = ["v4"] }
futures = "0.3"
